### ISSUE TITLE
More detailed catalog information

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/user-stories#12]
### User Profile

As a data library user

### User Action

I want to be able to see detailed information (e.g. variables, dimensions, attributes) about the datasets in the catalog

### User Goal

So that I can decide whether I want to use a particular dataset.

### Acceptance Criteria

- [ ] User browses to https://pangeo-forge.org/catalog an can click on a dataset (related to #1)
- [ ] Information is shown similar to the Xarray repr, or the legacy Pangeo catalog (e.g. https://catalog.pangeo.io/browse/master/ocean/SOSE/)
- [ ] Code samples show how to open the data in python.

### Linked Issues

- #1

**Comment by rabernat** [comment]
I think it is useful to think of the storage target location as a "data lake". So the key questions here are
- What services can we expect from the data lake? Currently we just assume that these are Zarr datasets in a bucket. But could the DL expose the metadata about the datasets via an API? 
- How should Pangeo Forge be identifying datasets in the DL? Currently we just pick a path (see [ADR-3](https://github.com/pangeo-forge/roadmap/blob/master/doc/adr/0003-standardize-storage-target-layout.md). However, we could use a different identifier system.

**Comment by abkfenris** [comment]
xpublish could be useful here as it exposes both the [xarray repr](https://github.com/xarray-contrib/xpublish/blob/498e86599083eabc7b8ba8dfad4348fe766e57aa/xpublish/routers/base.py#L11-L16) for datasets along with a [NCO-JSON](https://github.com/xarray-contrib/xpublish/blob/498e86599083eabc7b8ba8dfad4348fe766e57aa/xpublish/routers/base.py#L29-L54) representation.
